### ISSUE TITLE
pinpoint-quickstart not running

### ISSUE THREAD

**Issue by aldiyudhaa** [naver/pinpoint-docker#13]
Hi i've run docker-compose after that pinpoint-quickstart on port 8000 still not running but apache-flink is running well.
when i check netstat -an there is no port 8000.

can anyone help me for this issue?

**Comment by RoySRose** [comment]
Hello, @aldiyudhaa 

I've check recent docker images 
localhost 8000 runs fine.

try to check docker with below command in the container is running.
If not. try checking the log, usually, it's because the agent isn't found.
```text
docker ps
```

![image](https://user-images.githubusercontent.com/20402016/51969085-dc4a1080-24b6-11e9-8cfd-8502da6874d0.png)

**Comment by marcosamm** [comment]
I've check recent docker images
localhost 8000 not running

`docker ps -a`

CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                      PORTS                                                                                                                            NAMES
df4537556738        **pinpointdocker/pinpoint-quickstart**        "catalina.sh run"        31 seconds ago      **Exited (1) 27 seconds ago**                                                                                                                                    **pinpoint-quickstart**
5be3fe07caf1        pinpointdocker/pinpoint-agent:1.8.2       "/usr/local/bin/conf…"   35 seconds ago      Up 30 seconds                                                                                                                                                pinpoint-agent
7f54c10ecd92        pinpointdocker/pinpoint-web:1.8.2         "/usr/local/bin/star…"   36 seconds ago      Up 32 seconds               0.0.0.0:9997->9997/tcp, 0.0.0.0:8079->8080/tcp                                                                                   pinpoint-web
a43a77be7a3f        pinpointdocker/pinpoint-collector:1.8.2   "/usr/local/bin/star…"   40 seconds ago      Up 34 seconds               8080/tcp, 0.0.0.0:9994-9996->9994-9996/tcp, 0.0.0.0:9995-9996->9995-9996/udp                                                     pinpoint-collector
1ebc0ba8c910        flink:1.3.1                               "/docker-entrypoint.…"   41 seconds ago      Up 37 seconds               6123/tcp, 0.0.0.0:6121-6122->6121-6122/tcp, 0.0.0.0:19994->19994/tcp, 8081/tcp                                                   pinpoint-flink-taskmanager
1af627a56eef        zookeeper:3.4                             "/docker-entrypoint.…"   58 seconds ago      Up 38 seconds               2181/tcp, 2888/tcp, 3888/tcp                                                                                                     pinpoint-docker_zoo2_1_d024902968e9
c46004b31cae        pinpointdocker/pinpoint-mysql:1.8.2       "docker-entrypoint.s…"   58 seconds ago      Up 36 seconds               33060/tcp, 0.0.0.0:13306->3306/tcp                                                                                               pinpoint-mysql
c53cbf954c18        zookeeper:3.4                             "/docker-entrypoint.…"   58 seconds ago      Up 40 seconds               2181/tcp, 2888/tcp, 3888/tcp                                                                                                     pinpoint-docker_zoo1_1_b110b08d6a66
4e244f05cad6        flink:1.3.1                               "/docker-entrypoint.…"   58 seconds ago      Up 41 seconds               6123/tcp, 0.0.0.0:8081->8081/tcp                                                                                                 pinpoint-flink-jobmanager
2ba30ea59650        zookeeper:3.4                             "/docker-entrypoint.…"   58 seconds ago      Up 39 seconds               2181/tcp, 2888/tcp, 3888/tcp                                                                                                     pinpoint-docker_zoo3_1_5730d2baf67c
05a833ed5236        pinpointdocker/pinpoint-hbase:1.8.2       "/bin/sh -c '${BASE_…"   58 seconds ago      Up 40 seconds               0.0.0.0:16010->16010/tcp, 0.0.0.0:16030->16030/tcp, 0.0.0.0:60000->60000/tcp, 0.0.0.0:60020->60020/tcp, 0.0.0.0:2180->2181/tcp   pinpoint-hbase

`docker logs pinpoint-quickstart`

Error opening zip file or JAR manifest missing : /pinpoint-agent/pinpoint-bootstrap-1.8.2.jar
Error occurred during initialization of VM
agent library failed to init: instrument

**Comment by marcosamm** [comment]
Hello, @RoySRose

I discovered my problem.
For some reason I was using old images, even cloning the project with the latest versions of the files.
Solution: I removed the old containers and pinpoint images and ran the `docker-compose pull && docker-compose up -d` command

**Comment by RoySRose** [comment]
@marcosamm 

Thanks for sharing
