### ISSUE TITLE
yml or dockfile bug？

### ISSUE THREAD

**Issue by zhongyong** [naver/pinpoint-docker#28]
Error opening zip file or JAR manifest missing : /pinpoint-agent/pinpoint-bootstrap-1.8.4.jar
pinpointdocker/pinpoint-quickstart        "catalina.sh run"        52 seconds ago      Exited (1) 51 seconds ago

**Comment by RoySRose** [comment]
Yes, you were correct, I don't know why But, there was a problem with docker hub.
images were created with 1.8.3  tag, even if it was tagged as 1.8.4.
I didn't change anything but re-release 1.8.4 and everything became fine.
I've tested new images, all works fine. 

Thank you for the notice.
