### ISSUE TITLE
What is the right value of hbase.client.host for collector

### ISSUE THREAD

**Issue by manlinl** [naver/pinpoint-docker#29]
New to HBase and Pinpoint. I have a multi-nodes HBase. I want to use it with Pinpoint. What is the right value for hbase.client.host? One of the HBase's Zookeeper node IP? 

Many thx!

**Comment by RoySRose** [comment]
@manlinl 

Yes I believe it's correct
https://naver.github.io/pinpoint/installation.html#configuration
