### ISSUE TITLE
Pinpon-docker has mail notification

### ISSUE THREAD

**Issue by sidlors** [naver/pinpoint-docker#33]
Hi, I want to ask if this version has posibility to send mail alarms, I modified AlarmMessageSenderImple, then, I compiled project and move **AlarmMessageSenderImple.class**  inside pinpoint-web container in webapp/ROOT/WEB-INF/classes/com/navercorp/pinpoint/web/alarm/

```java
package com.navercorp.pinpoint.web.alarm;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.MailSender;
import org.springframework.mail.SimpleMailMessage;

import com.navercorp.pinpoint.web.alarm.checker.AlarmChecker;
import com.navercorp.pinpoint.web.service.UserGroupService;

public class AlarmMessageSenderImple implements AlarmMessageSender {

    private final Logger logger = LoggerFactory.getLogger(this.getClass());
    
    private MailSender mailSender;

    public void setMailSender(MailSender mailSender) {
	logger.info("debug1");
		this.mailSender = mailSender;
	}

	@Autowired
    private UserGroupService userGroupService;
    
    @Override
    public void sendSms(AlarmChecker checker, int sequenceCount) {
        List<String> receivers = userGroupService.selectPhoneNumberOfMember(checker.getuserGroupId());

        if (receivers.size() == 0) {
            return;
        }

        //for (String message : checker.getSmsMessage()) {
            logger.info("send SMS : {} TODO");

            // TODO Implement logic for sending SMS
        //}
    }

    @Override
    public void sendEmail(AlarmChecker checker, int sequenceCount) {
	logger.info("debug2");
	List<String> receivers = userGroupService.selectEmailOfMember(checker.getuserGroupId());

        if (receivers.size() == 0) {
            return;
        }

        logger.info("send email : {}", checker.getEmailMessage());
        try{
	        SimpleMailMessage message = new SimpleMailMessage(); 
	        message.setTo(receivers.toArray(new String [receivers.size()])); 
	        message.setSubject(String.format("[PINPOINT Alarm - %s]", checker.getRule().getApplicationId())); 
	        message.setText(String.format("%s\n\n%s", checker.getEmailMessage(), checker.getRule().getNotes()));
	        mailSender.send(message);
	logger.info("debug3");
        }catch(Exception e){
        	logger.error("send email error", e);
        }
    }
}
```

So if I watched log container:

```sh
docker logs -f pinpoint-web | grep AlarmMessageSenderImple
```

So, I only see inject method in log info:  **logger.info("debug1");** , but I never see sendEmail method I configured all files in web container, described on [https://naver.github.io/pinpoint/1.8.0/alarm.html](https://naver.github.io/pinpoint/1.8.0/alarm.html)

If I watch SQL Tables alarm_rule has my alert rows, but alarm_history doesn't have rows

Thanks in advace, so Sorry my poor english

**Comment by RoySRose** [comment]
Hello, @sidlors 

There were some changes in v1.8.3 for alarm implementations.
Until v1.8.2, You need to implement your own logic to use the alarm feature.
But since v1.8.3 it's already merged in the master, so the change of code is unnecessary.

Please try with v1.8.5 with [guide for v1.8.5](https://naver.github.io/pinpoint/1.8.5/alarm.html)

It will be great if you can give us feedback. I'll try to follow up this issue

**Comment by sidlors** [comment]
> Hello, @sidlors
> 
> There were some changes in v1.8.3 for alarm implementations.
> Until v1.8.2, You need to implement your own logic to use the alarm feature.
> But since v1.8.3 it's already merged in the master, so the change of code is unnecessary.
> 
> Please try with v1.8.5 with [guide for v1.8.5](https://naver.github.io/pinpoint/1.8.5/alarm.html)
> 
> It will be great if you can give us feedback. I'll try to follow up this issue

Thanks, actually. yeah, v1.8.5 working fine, I only had dab .env properties to send from gmail, I need create a application password [here. guide](https://devanswers.co/create-application-specific-password-gmail/)

Thanks !!
