### ISSUE TITLE
Question: How to view top 5 or 10 slow transaction in poinpoint web ui?

### ISSUE THREAD

**Issue by subusharma2001** [naver/pinpoint-docker#35]
Hello,

I want to know, how to get the top 5 or 10 slow transaction which is slowing as count in response summary graph?
![image](https://user-images.githubusercontent.com/34883636/72243239-641a2380-3611-11ea-81c3-c7400d4741d4.png)

**Comment by koo-taejin** [comment]
hi @subusharma2001 

Pinpoint does not yet support that feature.
Unfortunately, Pinpoint has no plans for that functionality too.

I think it would be very helpful if you develop the feature and contribute it to Pinpoint.

thanks :)

**Comment by subusharma2001** [comment]
Hi,

When i can expect pinpoint 1.9.0 version release?

**Comment by koo-taejin** [comment]
@subusharma2001 

Pinpoint goes for to release 2.0.0 this month.
But If we will find bug that is solving, then It can not be as planned. 

thanks :)
