### ISSUE TITLE
Question: How to view my application method name in call tree for a transaction?

### ISSUE THREAD

**Issue by subusharma2001** [naver/pinpoint-docker#36]
Hello,

I want to see my java method which took more time in call tree as of now i can see only sql statement under invoke method. I used profiler.include configuration in pinpoint.config file but it show warn msg that "**[WARN ](c.n.p.p.i.ASMMethod) Skip adding interceptor. 'abstract or native method' class=**". Could you please help me to configure java method includes in call tree?
![image](https://user-images.githubusercontent.com/34883636/72495668-5d77f000-384d-11ea-9a73-9b16b7a1d24c.png)

Thank You.
Subodh

**Comment by koo-taejin** [comment]
hi @subusharma2001 

Please post issue in the pinpoint repository.
(https://github.com/naver/pinpoint/issues)

thanks :)
