### ISSUE TITLE
How to install and deploy pinpoint after the jar file is deleted?Where should I find the jar files for installation?

### ISSUE THREAD

**Issue by Zhaoyang123** [naver/pinpoint-docker#67]
When installing and deploying pinpoint, I need to manually upload the pinpoint-Flink-job - {pinpoint version}. Jar file into the Flik component.But now that the jar file has been deleted, where can I download or find a jar file that conforms to my own pinpoint version?

**Comment by RoySRose** [comment]
@Zhaoyang123 

Flink component is not required. 
Uploading pinpoint-Flink-job in the past was a mistake. 

To able inspector aggregation feature, you need to build the flink job. jar file by yourself.
