### ISSUE TITLE
Readme.md file question...

### ISSUE THREAD

**Issue by nibaboojit** [naver/pinpoint-docker#69]
It's nothing important, but... wouldn't it be right to reverse the order of line number 40 and 41?
```
git clone https://github.com/naver/pinpoint-docker.git
cd pinpoint-docker
git checkout {tag}
docker-compose pull && docker-compose up -d
```

**Comment by RoySRose** [comment]
what is the line number 40 and 41?

![image](https://user-images.githubusercontent.com/20402016/87903891-12f35c80-ca98-11ea-8dd5-038dd9802cc2.png)

**Comment by nibaboojit** [comment]
Sorry writed wrong line number.
line number 49 and 50.
![image](https://user-images.githubusercontent.com/7933160/88007003-f151ae00-cb47-11ea-94d6-c1d8e2ee89c2.png)

I think the order below is correct.
What do you think?
```
git clone https://github.com/naver/pinpoint-docker.git
cd pinpoint-docker
git checkout {tag}
docker-compose pull && docker-compose up -d
```

**Comment by RoySRose** [comment]
Oh, yes. 
I think you are right :)
If you'd like, you can make a PR on it.
